on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: "Android build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use specific Java version for sdkmanager to work
        uses: joschi/setup-jdk@v2
        with:
          java-version: "openjdk8"
          architecture: "x64"
      - name: Delete newer NDK version
        run: |
          rm -rf $ANDROID_HOME/ndk/22*
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
      - run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android
      - run: echo '::set-output name=NDK_TOOLCHAINS::${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin'
        id: android
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/cargo
        with:
          command: build
          args: --target armv7-linux-androideabi --release
        env:
          CC: ${{ steps.android.NDK_TOOLCHAINS }}/armv7a-linux-androideabi30-clang
          CXX: ${{ steps.android.NDK_TOOLCHAINS }}/armv7a-linux-androideabi30-clang++
          AR: ${{ steps.android.NDK_TOOLCHAINS }}/arm-linux-androideabi-ar
          LD: ${{ steps.android.NDK_TOOLCHAINS }}/arm-linux-androideabi-ld
          RANLIB: ${{ steps.android.NDK_TOOLCHAINS }}/arm-linux-androideabi-ranlib
